# Generated by Django 5.0.4 on 2025-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок блока')),
                ('description', models.TextField(verbose_name='Текст Заголовка')),
                ('img', models.ImageField(upload_to='static/img/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Главный блок',
            },
        ),
    ]
