# Generated by Django 5.0.4 on 2025-04-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'Главный блок'},
        ),
    ]
