# Generated by Django 5.0.4 on 2025-04-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_hero_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='HeroBlock',
        ),
    ]
