# Generated by Django 5.0.4 on 2025-04-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_hero_heroblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroblock',
            name='img',
            field=models.ImageField(upload_to='img/', verbose_name='Изображение'),
        ),
    ]
